### ISSUE TITLE
Question: how's the host-guest network performance?

### ISSUE THREAD

**Issue by curiousercreative** [johncolby/macOS-KVM#1]
Are you able to exceed 1GbE?

**Comment by johncolby** [comment]
I haven't tested this... I am not sure how or if it's even possible to test this on my particular setup, since my VM virtio network device is connected to a host bridge connected to my physical 1 GbE host NIC.

Maybe I could test it if I made some sort of dummy interface? But I haven't explored this.

Anyway, if I iperf the host from the guest, I do max the 1 GbE connection.

**Comment by curiousercreative** [comment]
@johncolby did you have to install any drivers in your macOS VM for the virtio network device? Maybe it's because I'm on Mojave, but I can't get this network device to show up in macOS: https://github.com/curiousercreative/OSX-KVM/blob/master/default.sh#L60

**Comment by johncolby** [comment]
Ahh right, macOS support for the virtio network interface was only added fairly recently (maybe preliminarily in Catalina, but I don't recall exactly). I'm using it under Big Sur with no trouble. I did not need to install any extra drivers; support is built-in by Apple.

**Comment by curiousercreative** [comment]
that might be a good reason for me to update then. another option I could explore is passing through my 10GbE PCIe device, but would be good to have it available to the host at the same time and just bridge it. My 1GbE bridge is only doing ~330Mb/s in host to guest (or reverse) iperf3 tests on vmxnet3 :(

**Comment by curiousercreative** [comment]
Yeah, I created a big sur VM and the virtio just works. host to guest shows 12Gb/s!

**Comment by johncolby** [comment]
Sweet, that is awesome news! Thanks for the update!!
